annual_finance_rate: 0.12
base_demand: 93.74074814346842
competitor_sensitivity: !!python/object/apply:numpy._core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  1HcVE5Guuz8=
demand_noise_scale: 0.05
holding_cost: !!python/object/apply:numpy._core.multiarray.scalar
- *id001
- !!binary |
  pxrDQDgf0j8=
holding_rate_k: 10.0
holding_rate_x0: 0.25
initial_inventory: 100
linear_base_rate: 0.02
linear_excess_penalty: 0.03
periods_per_year: 12
price_elasticity: !!python/object/apply:numpy._core.multiarray.scalar
- *id001
- !!binary |
  C+8niBIBvr8=
price_tiers:
- 25.0
- 35.0
- 40.0
- 45.0
- 47.5
- 50.0
- 52.5
- 55.00000000000001
- 60.0
- 65.0
product_category: Electronics
product_name: Sample Product
promotion_multiplier: 1.0232301442903777
region: North
region_effects:
  East: 0.9666806214919583
  North: 1.0
  South: 0.9887678516953857
  West: 0.9776618645463082
restock_amount: 150
restock_level: 50
restock_period: 5
season_effects:
  Autumn: 1.011028190210742
  Spring: 1.0
  Summer: 1.005498975738286
  Winter: 1.016587809699434
spoilage_pct: 0.001
stockout_penalty: 2.0
storage_fee: 0.1
unit_cost: 50
use_dynamic_holding_cost: true
use_fitted_model: true
use_linear_holding_cost: true
weather_effects:
  Cloudy: 0.9810555650501179
  Rainy: 0.9624700217158062
  Snowy: 0.9442365709981996
  Sunny: 1.0
